#sfynx_auth:
#    theme: 
#        name: flatlab # {'flatlab','smoothness'} 
#        login: "SfynxFlatlabBundle::Login\\"
#        layout: "SfynxFlatlabBundle::Layout\\"
#        email:
#            registration:
#                from_email:
#                    address: contact@sfynx.fr
#                template: SfynxFlatlabBundle:Login\\Registration:email.txt.twig
#            resetting:
#                from_email:
#                    address: contact@sfynx.fr
#                template: SfynxFlatlabBundle:Login\\Resetting:email.txt.twig 
#        global:
#            layout: "SfynxFlatlabBundle::Layout\\layout-global-cmf.html.twig"
#            css: "bundles/sfynxflatlab/layout/screen-layout-global.css"
#        ajax:
#            layout: "SfynxFlatlabBundle::Layout\\layout-ajax.html.twig"
#            css: "bundles/sfynxflatlab/layout/screen-layout-ajax.css"
#        error:
#            route_name: ~ # error_404
#            html: "@SfynxFlatlabBundle/Resources/views/Error/error.html.twig"
#        admin:
#            pc: "SfynxFlatlabBundle::Layout\\Pc\\"
#            mobile: "SfynxFlatlabBundle::Layout\\Mobile\\Admin\\"
#            css: "bundles/sfynxflatlab/admin/screen.css"
#            home: "SfynxFlatlabBundle:Home:admin.html.twig"  # SfynxAuthBundle:Frontend:index.html.twig
#            dashboard: "dashboard.default.html.twig"
#            grid:
#                img: "/bundles/sfynxflatlab/admin/grid/img/"
#                css: "bundles/sfynxflatlab/admin/grid.css"
#                type: simple
#                state_save: false
#                row_select: 'multi'  # multi, single
#                pagination: true 
#                pagination_type: "bootstrap"  # bootstrap, full_numbers, simple_numbers    
#                pagination_top: false
#                lengthmenu: 20
#                filters_tfoot_up: true
#                filters_active: false
#            form:
#                builder: "SfynxFlatlabBundle:Form"
#                template: "SfynxFlatlabBundle:Form:fields.html.twig" 
#                css: "bundles/sfynxflatlab/admin/form/form.css"  
#            flash: "SfynxFlatlabBundle:Flash:flash.html.twig"     
#        front:
#            pc: "SfynxFlatlabBundle::Layout\\Pc\\"
#            pc_path: "@SfynxFlatlabBundle/Resources/views/Layout/Pc/"
#            mobile: "SfynxFlatlabBundle::Layout\\Mobile\\"
#            mobile_path: "@SfynxFlatlabBundle/Resources/views/Layout/Mobile/"
#            css: ""
#        connexion:
#            login: "SfynxFlatlabBundle::Login\\Security\\login-layout.html.twig"
#            widget: "SfynxFlatlabBundle::Login\\Security\\connexion-widget.html.twig" 